### ISSUE TITLE
Calc needs to trap IOException during "exec" call

### ISSUE THREAD

**Issue by rlwhitcomb** [rlwhitcomb/utilities#85]
Currently the error for an unknown program comes out in a really bad form (this on Windows):
```
> exec('uuid')
Nov 16,2021 18:34:23.190 GMT P(143920) T[main](1) ERROR: java.io.IOException: Cannot run program "uuid": CreateProcess error=2, The system cannot find the file specified
```
If the exception were trapped and wrapped in a CalcExprException then it would be presented more cleanly.

**Comment by barismutan** [comment]
Hello, I would like to work on this issue.

**Comment by rlwhitcomb** [comment]
@barismutan That would be great, although I was just working on it and I think it's a bit harder than I thought....

**Comment by rlwhitcomb** [comment]
Solution coded on branch https://github.com/rlwhitcomb/utilities/tree/trap-calc-exec-exceptions-85

**Comment by rlwhitcomb** [comment]
@barismutan If you'd like to try your hand at this, you can start by forking my repository to your GitHub account, clone it locally (all branches), then take a look at my proposed changes in branch https://github.com/rlwhitcomb/utilities/tree/trap-calc-exec-exceptions-85. You can build a new .jar file to test with using "ant all-install".  I'm not entirely sure if my fixes completely address the problem, so more testing could be done.
